spring:
  profiles:
    active:  # 默认选择哪一个配置
      - producer2
---

server:
  port: 8081
spring:
  profiles: producer1  # 服务提供者1
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ccat
    url: jdbc:mysql://127.0.0.1:3306/re?characterEncoding=utf-8
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5


--- 
    
server:
  port: 8083
spring: 
  profiles: producer2  # 服务提供者1 
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ccat
    url: jdbc:mysql://127.0.0.1:3306/re?characterEncoding=utf-8
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5